package com.edu.hello.mapper;

import com.edu.hello.entity.email;
import com.edu.hello.entity.emailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface emailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbg.generated
     */
    long countByExample(emailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbg.generated
     */
    int deleteByExample(emailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbg.generated
     */
    int insert(email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbg.generated
     */
    int insertSelective(email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbg.generated
     */
    List<email> selectByExample(emailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbg.generated
     */
    email selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") email record, @Param("example") emailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") email record, @Param("example") emailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(email record);
}