package com.edu.hello.entity;

public class CouponGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_goods.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_goods.coupon_id
     *
     * @mbg.generated
     */
    private Long couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_goods.enterprise_id
     *
     * @mbg.generated
     */
    private Long enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_goods.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_goods.sku_id
     *
     * @mbg.generated
     */
    private Long skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_goods.spu_id
     *
     * @mbg.generated
     */
    private Long spuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_goods.updated_at
     *
     * @mbg.generated
     */
    private Integer updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_goods.created_at
     *
     * @mbg.generated
     */
    private Integer createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_goods.deleted_at
     *
     * @mbg.generated
     */
    private Integer deletedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_goods.id
     *
     * @return the value of coupon_goods.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_goods.id
     *
     * @param id the value for coupon_goods.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_goods.coupon_id
     *
     * @return the value of coupon_goods.coupon_id
     *
     * @mbg.generated
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_goods.coupon_id
     *
     * @param couponId the value for coupon_goods.coupon_id
     *
     * @mbg.generated
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_goods.enterprise_id
     *
     * @return the value of coupon_goods.enterprise_id
     *
     * @mbg.generated
     */
    public Long getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_goods.enterprise_id
     *
     * @param enterpriseId the value for coupon_goods.enterprise_id
     *
     * @mbg.generated
     */
    public void setEnterpriseId(Long enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_goods.type
     *
     * @return the value of coupon_goods.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_goods.type
     *
     * @param type the value for coupon_goods.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_goods.sku_id
     *
     * @return the value of coupon_goods.sku_id
     *
     * @mbg.generated
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_goods.sku_id
     *
     * @param skuId the value for coupon_goods.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_goods.spu_id
     *
     * @return the value of coupon_goods.spu_id
     *
     * @mbg.generated
     */
    public Long getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_goods.spu_id
     *
     * @param spuId the value for coupon_goods.spu_id
     *
     * @mbg.generated
     */
    public void setSpuId(Long spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_goods.updated_at
     *
     * @return the value of coupon_goods.updated_at
     *
     * @mbg.generated
     */
    public Integer getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_goods.updated_at
     *
     * @param updatedAt the value for coupon_goods.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Integer updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_goods.created_at
     *
     * @return the value of coupon_goods.created_at
     *
     * @mbg.generated
     */
    public Integer getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_goods.created_at
     *
     * @param createdAt the value for coupon_goods.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Integer createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_goods.deleted_at
     *
     * @return the value of coupon_goods.deleted_at
     *
     * @mbg.generated
     */
    public Integer getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_goods.deleted_at
     *
     * @param deletedAt the value for coupon_goods.deleted_at
     *
     * @mbg.generated
     */
    public void setDeletedAt(Integer deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_goods
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", couponId=").append(couponId);
        sb.append(", enterpriseId=").append(enterpriseId);
        sb.append(", type=").append(type);
        sb.append(", skuId=").append(skuId);
        sb.append(", spuId=").append(spuId);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", deletedAt=").append(deletedAt);
        sb.append("]");
        return sb.toString();
    }
}