package com.edu.hello.entity;

public class email {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.id_crc
     *
     * @mbg.generated
     */
    private String idCrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.created_at
     *
     * @mbg.generated
     */
    private Integer createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.deleted_at
     *
     * @mbg.generated
     */
    private Integer deletedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.updated_at
     *
     * @mbg.generated
     */
    private Integer updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.id
     *
     * @return the value of email.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.id
     *
     * @param id the value for email.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.email
     *
     * @return the value of email.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.email
     *
     * @param email the value for email.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.id_crc
     *
     * @return the value of email.id_crc
     *
     * @mbg.generated
     */
    public String getIdCrc() {
        return idCrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.id_crc
     *
     * @param idCrc the value for email.id_crc
     *
     * @mbg.generated
     */
    public void setIdCrc(String idCrc) {
        this.idCrc = idCrc == null ? null : idCrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.created_at
     *
     * @return the value of email.created_at
     *
     * @mbg.generated
     */
    public Integer getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.created_at
     *
     * @param createdAt the value for email.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Integer createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.deleted_at
     *
     * @return the value of email.deleted_at
     *
     * @mbg.generated
     */
    public Integer getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.deleted_at
     *
     * @param deletedAt the value for email.deleted_at
     *
     * @mbg.generated
     */
    public void setDeletedAt(Integer deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.updated_at
     *
     * @return the value of email.updated_at
     *
     * @mbg.generated
     */
    public Integer getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.updated_at
     *
     * @param updatedAt the value for email.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Integer updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", email=").append(email);
        sb.append(", idCrc=").append(idCrc);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", deletedAt=").append(deletedAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append("]");
        return sb.toString();
    }
}